 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/especialidades", type: :request do
  # Especialidade. As you add validations to Especialidade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Especialidade.create! valid_attributes
      get especialidades_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      especialidade = Especialidade.create! valid_attributes
      get especialidade_url(especialidade)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_especialidade_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      especialidade = Especialidade.create! valid_attributes
      get edit_especialidade_url(especialidade)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Especialidade" do
        expect {
          post especialidades_url, params: { especialidade: valid_attributes }
        }.to change(Especialidade, :count).by(1)
      end

      it "redirects to the created especialidade" do
        post especialidades_url, params: { especialidade: valid_attributes }
        expect(response).to redirect_to(especialidade_url(Especialidade.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Especialidade" do
        expect {
          post especialidades_url, params: { especialidade: invalid_attributes }
        }.to change(Especialidade, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post especialidades_url, params: { especialidade: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested especialidade" do
        especialidade = Especialidade.create! valid_attributes
        patch especialidade_url(especialidade), params: { especialidade: new_attributes }
        especialidade.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the especialidade" do
        especialidade = Especialidade.create! valid_attributes
        patch especialidade_url(especialidade), params: { especialidade: new_attributes }
        especialidade.reload
        expect(response).to redirect_to(especialidade_url(especialidade))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        especialidade = Especialidade.create! valid_attributes
        patch especialidade_url(especialidade), params: { especialidade: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested especialidade" do
      especialidade = Especialidade.create! valid_attributes
      expect {
        delete especialidade_url(especialidade)
      }.to change(Especialidade, :count).by(-1)
    end

    it "redirects to the especialidades list" do
      especialidade = Especialidade.create! valid_attributes
      delete especialidade_url(especialidade)
      expect(response).to redirect_to(especialidades_url)
    end
  end
end
